### ISSUE TITLE
[Bugs] Crash and rendering problems

### ISSUE THREAD

**Issue by Matthysse** [Pannoniae/sodium-forge#13]
Hello!
Here is a crash between your port and an entity from Upgrade Aquatic, if I understand correctly : https://pastebin.com/8jXjmGng

And I have many rendering problems:
Lines between blocks: (seems to happen only with the Wallpapercraft mod ?)
![2021-01-10_21 06 41](https://user-images.githubusercontent.com/32510957/104134227-9b3c2580-5388-11eb-9e56-c95260684d9a.png)

And moving parts in 3D models of block don't appear (supposed to be a globe and clocks):
![2021-01-10_21 07 55](https://user-images.githubusercontent.com/32510957/104134245-b4dd6d00-5388-11eb-8ab5-024223e83cff.png)

And problems with transparent blocks (vanilla colored stained glass and endergetic blocks):
![2021-01-13_21 47 04](https://user-images.githubusercontent.com/32510957/104509494-0e90a200-55ea-11eb-9345-0e57888877d0.png)

I really wish these problems could be fixed, as this mod is really better than optifine on my really large modpack. Keep up the good work!

**Comment by yatsukiko** [comment]
Should be fixed, multipart block are now rendered. For lines between blocks, disable "compact vertex format". For the crash, it's something I can't fix now so instead I disable it, here is a [compiled version that should work](https://yatsukiko.me/u/sodium-forge-1.101.jar) (this "special" version doesn't support mulipart rendering, it's just a temporary fix)

**Comment by Matthysse** [comment]
There is an incompatibility with charm:
https://pastebin.com/xTnMd6Fk
And nothing changes for me (no rendering of multipart and transparency):
![2021-02-14_11 24 37](https://user-images.githubusercontent.com/32510957/107874098-6f481e80-6eb7-11eb-811e-c5328db53240.png)

**Comment by yatsukiko** [comment]
crash is because charm failed to mixin inject not sure is it sodiumophosphorolithium's fault, for not  rendering properly, can you try this? https://yatsukiko.me/u/sodium-forge-2.0.jar also make sure your quality settings is **not** "Fabulous"

**Comment by Matthysse** [comment]
Multiparts work thanks!
Transparent objects are still not transparent, and I'm on Fancy graphics, not fabulous.
![2021-02-14_19 47 25](https://user-images.githubusercontent.com/32510957/107886297-33d14280-6eff-11eb-9238-76334ad7e175.png)
